export enum PIZZAS_TYPES {
  GET_PIZZAS = "GET_PIZZAS",
  ERROR_PIZZAS = "ERROR_PIZZAS",
}
export enum STATUSES {
  LOADED = "LOADED",
  LOADING = "LOADING",
  ERROR = "ERROR",
}
export enum CART_TYPES {
  ADD_PIZZA = "ADD_PIZZA",
  REMOVE_PIZZA = "REMOVE_PIZZA",
  CLEAR_CART = "CLEAR_CART",
  MINUS_PIZZA = "MINUS_PIZZA",
}
